[package]
name = "snake_webassembly"
version = "0.1.0"
authors = ["Alberto-Izquierdo <alberto.izquierdo.ramirez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
